// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: dlrepos.sql

package database

import (
	"context"
)

const reposInsert = `-- name: ReposInsert :exec

INSERT INTO repos (owner_name, repo_name, last_ts)
VALUES (?, ?, UNIXEPOCH())
ON CONFLICT (owner_name, repo_name)
DO NOTHING
`

type ReposInsertParams struct {
	OwnerName string
	RepoName  string
}

func (q *Queries) ReposInsert(ctx context.Context, arg ReposInsertParams) error {
	_, err := q.db.ExecContext(ctx, reposInsert, arg.OwnerName, arg.RepoName)
	return err
}
