// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package database

import ()

type Donation struct {
	ID               int64
	SponsorID        string
	RecipientID      string
	LastTs           int64
	AnimateTs        int64
	AnimateAttemptTs int64
	DonableTs        int64
	DonateTs         int64
	DonateAttemptTs  int64
}
