// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package database

import (
	"database/sql"
)

type Donation struct {
	ID              int64
	SponsorID       string
	RecipientID     string
	LastTs          int64
	DonateTs        int64
	DonateAttemptTs int64
}

type Repo struct {
	OwnerName      string
	RepoName       string
	LastTs         int64
	CursorManifest sql.NullString
	CursorDep      sql.NullString
	AnimateTs      int64
}
