// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: query.sql

package database

import (
	"context"
)

const insertDonation = `-- name: InsertDonation :exec

INSERT INTO donations (sponsor_id, recipient_id, last_ts)
VALUES (?, ?, ?)
ON CONFLICT (sponsor_id, recipient_id)
DO NOTHING
`

type InsertDonationParams struct {
	SponsorID   string
	RecipientID string
	LastTs      int64
}

func (q *Queries) InsertDonation(ctx context.Context, arg InsertDonationParams) error {
	_, err := q.db.ExecContext(ctx, insertDonation, arg.SponsorID, arg.RecipientID, arg.LastTs)
	return err
}
