// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: wkranimate.sql

package database

import (
	"context"
)

const getAnimatables = `-- name: GetAnimatables :many

SELECT id, sponsor_id, recipient_id
FROM donations
WHERE
	animate_ts < last_ts AND
	animate_attempt_ts < UNIXEPOCH() - 3600
`

type GetAnimatablesRow struct {
	ID          int64
	SponsorID   string
	RecipientID string
}

func (q *Queries) GetAnimatables(ctx context.Context) ([]GetAnimatablesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAnimatables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAnimatablesRow
	for rows.Next() {
		var i GetAnimatablesRow
		if err := rows.Scan(&i.ID, &i.SponsorID, &i.RecipientID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDonationAnimateAttemptTs = `-- name: UpdateDonationAnimateAttemptTs :exec

UPDATE donations
SET animate_attempt_ts = UNIXEPOCH()
WHERE id = ?
`

func (q *Queries) UpdateDonationAnimateAttemptTs(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateDonationAnimateAttemptTs, id)
	return err
}

const updateDonationAnimateTs = `-- name: UpdateDonationAnimateTs :exec

UPDATE donations
SET animate_ts = UNIXEPOCH()
WHERE id = ?
`

func (q *Queries) UpdateDonationAnimateTs(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateDonationAnimateTs, id)
	return err
}

const updateDonationDonableAnimateTs = `-- name: UpdateDonationDonableAnimateTs :exec

UPDATE donations
SET
	animate_ts = UNIXEPOCH(),
	donable_ts = UNIXEPOCH()
WHERE id = ?
`

func (q *Queries) UpdateDonationDonableAnimateTs(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateDonationDonableAnimateTs, id)
	return err
}
