// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: wkrtd.sql

package database

import (
	"context"
)

const insertDonation = `-- name: InsertDonation :exec

INSERT INTO donations (sponsor_id, recipient_id, last_ts)
VALUES (?, ?, UNIXEPOCH())
ON CONFLICT (sponsor_id, recipient_id)
DO UPDATE
	SET last_ts = EXCLUDED.last_ts
`

type InsertDonationParams struct {
	SponsorID   string
	RecipientID string
}

func (q *Queries) InsertDonation(ctx context.Context, arg InsertDonationParams) error {
	_, err := q.db.ExecContext(ctx, insertDonation, arg.SponsorID, arg.RecipientID)
	return err
}
